olist_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: olist_user
      pass: olist_password
      dbname: olist_db
      schema: public
